version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=TheGibson
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud

  nc:
    image: nextcloud:27.0.2-apache
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_PASSWORD=TheGibson
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=db