version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:11.0.2-jammy
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TheGibson
      - MYSQL_PASSWORD=TheGibson
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nc:
    image: nextcloud:30.0.0-apache
    #build: # The build takes currently ~ 30 minutes which is far too long for daily testing
    #  context: ../29/fpm
    #  dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=TheGibson
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    healthcheck:
      test: curl --fail --silent http://nc
      interval: "1h" # effectively turns repeated healthchecks during runtime off
      start_period: "60s"
      start_interval: "1s"
