version: '2'

services:
  nc:
    image: nextcloud:29.0.5-apache
    #build: # The build takes currently ~ 30 minutes which is far too long for daily testing
    #  context: ../29/fpm
    #  dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    #volumes:
    #  - nextcloud:/var/www/html # This is the usual way of using nextcloud in a container, but we do not need persistent data storage for benchmarking
    healthcheck:
      test: curl --fail --silent http://nc
      interval: "1h" # effectively turns repeated healthchecks during runtime off
      start_period: "60s"
      start_interval: "1s"
