---
name: Nextcloud - Postgres - Talk - Chromium
author: Danilo Jesic <danilo@green-coding.berlin>
description: Installs the official Nextcloud image with a Postgres and starts a Talk conversation. Uses a playwright script running Chromium to create an admin account, install the recommended apps and then create a Talk conversation where guest users will send each other random text.
compose-file: !include compose-postgres.yml

sci:
  R_d: Talk message

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v9
    depends_on:
      nc:
        condition: service_started # change to service_healthy when Docker CE 25.0 is released which supports start-interval
#    volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode

flow:
  - name: Install Nextcloud
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_install.py
        note: Installing Nextcloud
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true
  - name: Talk conversation
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_talk.py
        note: Starting conversation
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true
