---
name: NextCloud MariaDB - Chrome Talk
author: Danilo Jesic <danilo@green-coding.berlin>
version: 1
description: Installs the official NextCloud image and starts a Talk conversation
compose-file: !include compose.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright
    setup-commands:
      - cp /tmp/repo/nextcloud_install_playwright.py /tmp/nextcloud_install_playwright.py
      - cp /tmp/repo/nextcloud_talk_playwright.py /tmp/nextcloud_talk_playwright.py

    networks:
      - nextcloud-setup-network
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    #   DISPLAY: ":0"

  # We don't need the volumes are we don't want to persist any data
  db:
    volumes: []
    networks:
      - nextcloud-setup-network

  nc:
    volumes: []
    networks:
      - nextcloud-setup-network

networks:
  nextcloud-setup-network:

flow:
  - name: Check Website
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/nextcloud_install_playwright.py
        note: Installing Nextcloud
        read-notes-stdout: true
      - type: console
        command: python3 /tmp/nextcloud_talk_playwright.py
        note: Creating Event
        read-notes-stdout: true
